export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"; 

export const POST_DATA_SEND_START = "POST_DATA_SEND_START";
export const POST_DATA_SEND_SUCCESS = "POST_DATA_SEND_SUCCESS";
export const POST_DATA_SEND_FAILED = "POST_DATA_SEND_FAILED";